stages:
- test
- publish

before_script:
- scripts/ci/install-deps
- pip install -r requirements-test.txt
- python setup.py install

test:
  stage: test
  script:
  - pytest

publish:
  only:
  - tags
  stage: publish
  script:
  - pip install twine wheel
  - python setup.py sdist bdist_wheel
  - twine upload dist/kubeobject-*
