#!/usr/bin/env bash

export PATH=$PATH:$HOME/bin

echo "Installing kubectl"
KUBE_VER="v1.14.0"
curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/${KUBE_VER}/bin/linux/amd64/kubectl"
chmod +x kubectl
mv kubectl $HOME/bin

echo "Installing minikube"
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
chmod +x minikube
mv minikube $HOME/bin

echo "Starting minikube"
minikube start --memory=4096 --vm-driver=none --kubernetes-version="v${TEST_CLUSTER_version}" --extra-config=apiserver.v=10
# chown -R $USER ${HOME}/.{mini,}kube
kubectl config use-context minikube
